//
//  IndiaLanguage.swift
//  india_states
//
//  Created by Nate Brown on 7/25/21.
//

import Foundation

// https://www.jagranjosh.com/general-knowledge/list-of-official-languages-of-indian-states-and-union-territories-1624022980-1
enum IndiaLanguage: String {
  case ENGLISH = "English"
  case TELUGU = "Telugu"
  case ASSAMESE = "Asssamese"
  case HINDI = "Hindi"
  case BENGALI = "Bengali"
  case BODO = "Bodo"
  case URDU = "Urdu"
  case CHHATTISGARHI = "Chhattisgarhi"
  case KONKANI = "Konkani"
  case MARATHI = "Marathi"
  case GUJARATI = "Gujarati"
  case PUNJABI = "Punjabi"
  case SANSKRIT = "Sanskrit"
  case ANGIKA = "Angika"
  case BHOJPURI = "Bhojpuri"
  case HO = "Ho"
  case KHARIA = "Kharia"
  case KHORTHA = "Khortha"
  case KURMALI = "Kurmali"
  case KURUKH = "Kurukh"
  case MAGAHI = "Magahi"
  case MAITHILI = "Maithili"
  case MUNDARI = "Mundari"
  case NAGPURI = "Nagpuri"
  case ODIA = "Odia"
  case SANTALI = "Santali"
  case KANNADA = "Kannada"
  case MALAYALAM = "Malayalam"
  case MANIPURI = "Mainpuri"
  case KHASI = "Khasi"
  case GARO = "Garo"
  case MIZO = "Mizo"
  case NEPALI = "Nepali"
  case SIKKIMESE = "Sikkimese"
  case LEPCHA = "Lepcha"
  case GURUNG = "Gurung"
  case LIMBU = "Limbu"
  case MAGAR = "Magar"
  case MUKHIA = "Mukhia"
  case NEWARI = "Newari"
  case RAI = "Rai"
  case SHERPA = "Sherpa"
  case TAMANG = "Tamang"
  case TAMIL = "Tamil"
  case KOKBOROK = "Kokborok"
  case KAMTAPURI = "Kamptapuri"
  case RAJBANSHI = "Rajbanshi"
  case KASHMIRI = "Kashmiri"
  case DOGRI = "Dogri"
  case FRENCH = "French"
  
  func getLink() -> String {
    switch self {
    case .ENGLISH: return "https://en.wikipedia.org/wiki/Indian_English"
    case .TELUGU: return "https://en.wikipedia.org/wiki/Telugu_language"
    case .ASSAMESE: return "https://en.wikipedia.org/wiki/Assamese_language"
    case .HINDI: return "https://en.wikipedia.org/wiki/Hindi"
    case .BENGALI: return "https://en.wikipedia.org/wiki/Bengali_language"
    case .BODO: return "https://en.wikipedia.org/wiki/Boro_language_(India)"
    case .URDU: return "https://en.wikipedia.org/wiki/Urdu"
    case .CHHATTISGARHI: return "https://en.wikipedia.org/wiki/Chhattisgarhi_language"
    case .KONKANI: return "https://en.wikipedia.org/wiki/Konkani_language"
    case .MARATHI: return "https://en.wikipedia.org/wiki/Marathi_language"
    case .GUJARATI: return "https://en.wikipedia.org/wiki/Gujarati_language"
    case .PUNJABI: return "https://en.wikipedia.org/wiki/Punjabi_language"
    case .SANSKRIT: return "https://en.wikipedia.org/wiki/Sanskrit"
    case .ANGIKA: return "https://en.wikipedia.org/wiki/Angika"
    case .BHOJPURI: return "https://en.wikipedia.org/wiki/Bhojpuri_language"
    case .HO: return "https://en.wikipedia.org/wiki/Ho_language"
    case .KHARIA: return "https://en.wikipedia.org/wiki/Kharia_language"
    case .KHORTHA: return "https://en.wikipedia.org/wiki/Khortha_language"
    case .KURMALI: return "https://en.wikipedia.org/wiki/Kurmali_language"
    case .KURUKH: return "https://en.wikipedia.org/wiki/Kurukh_language"
    case .MAGAHI: return "https://en.wikipedia.org/wiki/Magahi_language"
    case .MAITHILI: return "https://en.wikipedia.org/wiki/Maithili_language"
    case .MUNDARI: return "https://en.wikipedia.org/wiki/Mundari_language"
    case .NAGPURI: return "https://en.wikipedia.org/wiki/Sadri_language"
    case .ODIA: return "https://en.wikipedia.org/wiki/Odia_language"
    case .SANTALI: return "https://en.wikipedia.org/wiki/Santali_language"
    case .KANNADA: return "https://en.wikipedia.org/wiki/Kannada"
    case .MALAYALAM: return "https://en.wikipedia.org/wiki/Malayalam"
    case .MANIPURI: return "https://en.wikipedia.org/wiki/Meitei_language"
    case .KHASI: return "https://en.wikipedia.org/wiki/Khasi_language"
    case .GARO: return "https://en.wikipedia.org/wiki/Garo_language"
    case .MIZO: return "https://en.wikipedia.org/wiki/Mizo_language"
    case .NEPALI: return "https://en.wikipedia.org/wiki/Nepali_language"
    case .SIKKIMESE: return "https://en.wikipedia.org/wiki/Sikkimese_language"
    case .LEPCHA: return "https://en.wikipedia.org/wiki/Lepcha_language"
    case .GURUNG: return "https://en.wikipedia.org/wiki/Gurung_language"
    case .LIMBU: return "https://en.wikipedia.org/wiki/Limbu_language"
    case .MAGAR: return "https://en.wikipedia.org/wiki/Magar_language"
    case .MUKHIA: return "https://en.wikipedia.org/wiki/Sunwar_language"
    case .NEWARI: return "https://en.wikipedia.org/wiki/Newar_language"
    case .RAI: return "https://en.wikipedia.org/wiki/Rai_language"
    case .SHERPA: return "https://en.wikipedia.org/wiki/Sherpa_language"
    case .TAMANG: return "https://en.wikipedia.org/wiki/Tamang_language"
    case .TAMIL: return "https://en.wikipedia.org/wiki/Tamil_language"
    case .KOKBOROK: return "https://en.wikipedia.org/wiki/Kokborok"
    case .KAMTAPURI: return "https://en.wikipedia.org/wiki/KRNB_lects"
    case .RAJBANSHI: return "https://en.wikipedia.org/wiki/Rajbanshi_language_(Nepal)"
    case .KASHMIRI: return "https://en.wikipedia.org/wiki/Kashmiri_language"
    case .DOGRI: return "https://en.wikipedia.org/wiki/Dogri_language"
    case .FRENCH: return "https://en.wikipedia.org/wiki/French_language"
    }
  }
}
